"""Agregamos el booleano de estaOculto

Revision ID: 593851e3b0a9
Revises: 
Create Date: 2022-09-13 15:49:55.775364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593851e3b0a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactos', sa.Column('estaOculto', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contactos', 'estaOculto')
    # ### end Alembic commands ###
