"""estaOculto va en False

Revision ID: 9e16a79e7058
Revises: 98643a6f9406
Create Date: 2022-09-13 15:53:27.692729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e16a79e7058'
down_revision = '98643a6f9406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personas', 'estaOculto',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personas', 'estaOculto',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
